theme:  jekyll-theme-minimal
title:  "Virt-EU project"
description:  "This page provides information about data collected from Twitter by Uppsala University for the European Project: “Virt-EU: Values and Ethics in Innovation for Responsible Technology in Europe” (grant agreement No 732027)."
logo: "virt-eu_NEG.jpg"
show_downloads: false
